### ISSUE TITLE
[BUG] App CRASHES when you try to log out or delete your account - I does the tasks properly - but after returning to the sign in page firebase auth (can be our getCurrent_user_id() method in firebase utility class) tries to reach to a user id that becomes null.

### ISSUE THREAD

**Issue by begeli** [2018-SWENG/2018-SWENG-Radius#169]

**Comment by X4l1b1** [comment]
The issue is that the session with Google/FirebaseAuth is terminated but it is all that is done. Thus, the FirebaseUtility is still active, along with other classes, and try to access to the user's current ID, which makes the App crash.
I've imagined two ways to solve this : 
> Upon either action (disconnect, delete acccount), switch the used ID (from FirebaseAuth) from a local instance (i.e. check if we have a  FirebaseAuth session before requesting)
> Upon either action (both leading back to the MainActivity sign-in view), nuke the app and relaunch it from scratch

Second one seems cleaner but harder to implement.
