### ISSUE TITLE
Integrate CodeClimate

### ISSUE THREAD

**Issue by SolalPirelli** [2018-SWENG/2018-SWENG-Radius#39]

**Comment by SolalPirelli** [comment]
Please have working CodeClimate badges ASAP so that we can include them in the [SDP dashboard](https://dslab.epfl.ch/teaching/sweng/proj#project-dashboard-fall-2018). Thanks!

**Comment by X4l1b1** [comment]
Hello,

Codeclimate, despite the travis file being configured as instructed un the bootcamp and integrated to Travis CI with the Report ID, doesnt seem to work.
The. /gradlew jacocoTestReport returns normally with 0 but both following executions of. /cc-test-report generate errors due to missing files.

As It is hard to reproduce what travis does locally, this issue remains to be fixed for now. Our priority for now is to implement the 80% test coverage.

**Comment by SolalPirelli** [comment]
Get coverage and diff-coverage shown in the PRs

**Comment by Fanfou02** [comment]
Done
